### ISSUE TITLE
Support for Flow Types

### ISSUE THREAD

**Issue by ignaciopicun** [biletskyy/flatwhite-syntax#30]
Hi! I've been messing around with some styles to add support for flow syntax and I've come with this styles, I've never worked with Atom syntax before so probably this is not the best solution for this but I think that maybe you can figure out how to add them (and probably select some better colors for this).

Thank you very much!

```less
.syntax--source.syntax--js {
  .syntax--keyword.syntax--operator.syntax--optional.syntax--parameter.syntax--flowtype {
    // .syntax-blue;
    color: #4c5361;
    background-color: rgba(117, 163, 255, 0.2);
  }
  .syntax--support.syntax--type.syntax--flowtype {
    // .syntax-teal;
    color: #4c5361;
    background-color: rgba(0, 189, 164, 0.15);

    &.syntax--builtin {
      // .syntax-orange;
      color: hsl(35, 15%, 31%);
      background-color: hsla(35, 100%, 47%, 0.18);
    }
  }
}
```
